

#Loading

```{r}
#| echo: false
#| message: false
#| warning: false
# Load libraries
library(flextable)
library(officer)
library(dplyr)
library(knitr)
library(kableExtra)
library(gt)
library(gtsummary)
library(tidyverse)
library(jsonlite)
library(stringr)
library(ggplot2)
library(purrr) 
library(tidyr)
library(data.table)
library(tidytext)
library(glue)
library(tidygraph)
library(ggraph)
library(tibble)
library(flextable)
library(slam)         
library(quanteda)     
library(topicmodels) 
library(topicdoc) 
#library(word2vec)
library(Matrix)
library(tm)

```

# 1. PH Stats

```{r}
# file path
# =================
data_dir <- '.../Data/'
#setwd(data_dir)

output_path <-paste0(data_dir, 'Code for replication')
output_path_m<-paste0(data_dir, 'Code for replication/model')

```


```{r}
business <- paste0(data_dir,'merged_ph_dataclean0319.csv') #list()
user <- paste0(data_dir,'user_stat0319.csv')
review <- paste0(data_dir,'all_philly_reviews.csv')



business_dt<-read.csv(business)
dim(business_dt) #280112

user_dt<- read.csv(user)
review_dt<- read.csv(review)
user_review <- review_dt  |> 
  semi_join(business_dt, by = "user_id")  |> 
  filter(nchar(as.character(text)) > 0) |> 
  select(-date)
#dim(user_review)#485191


bs_attr<-read.csv(paste0(data_dir,'Business_attribute0319.csv'))
head(bs_attr)
```

# 2. LDA & Omnivore Results

```{r}
#LDA Model & Results
#========================
lda <- readRDS(paste0(output_path_m,"/lda_model_k50.rds"))
lda_dtm5<-readRDS(paste0(output_path_m,"/lda_dtm_filter5.rds"))
#top8_business_attr <- read.csv( paste0(output_path,"/file/top8_business_topic50_dtm5.csv")
user_topic_df<- readRDS(paste0(output_path_m,'/user_topic_df.rds'))



#User-level information & Gini coefficient
#======================================================

user_gini_df<-readRDS(paste0(output_path_m,'/user_gini_df.rds'))
head(user_gini_df)

gini_table <-user_gini_df |> 
          summarise(
            Variable = c("Orginal Gini","Residualized Gini"),
            N = c(n(), n()),
            Median = c(median(gini),median(gini2)),
            Mean = c(mean(gini),mean(gini2)),
            IQR    = c(IQR(gini),IQR(gini2)),
            Min = c(min(gini),min(gini2)),
            Max = c(max(gini),max(gini2))) |> 
  mutate(across(Median:Max, ~ round(., 3)))
#print(gini_table)


#Omnivore users
#================
omnivore_threshold <- quantile(user_gini_df$gini2, 0.3)
omnivore_user <- readRDS(paste0(output_path_m,'/omnivore_user_list.rds'))
# omnivore_user <- user_gini_df |>
#   filter(gini2 < omnivore_threshold) |>
#   select(user_id)


cat("There are", nrow(omnivore_user), "omnivore users.", round(nrow(omnivore_user) / nrow(user_gini_df) * 100,2), "% of all users are omnivores(Gini index threshold:",round(omnivore_threshold,3),").\n")


```




# 3. Taste-based Social Network Homophily
    
```{r}
# List of All PH User & Friend 
#===============================
friend_network <-read.csv(paste0(data_dir,'user_friend_list0319.csv'))

# List of Ominivores & Friend
omni_friend_network <- friend_network  |> 
  filter(user_id %in% omnivore_user$user_id ) 


cat("In Philadelphia dataset, there are", nrow(friend_network), "friend pairs in total. Among them there are", length(unique(friend_network$user_id)), "unique users(both omnivores and normal users) and",  length(unique(friend_network$friends_id)), "unique friends.\n
For omnivore group only, there are", nrow(omni_friend_network), "omnivore's actual friend pairs in total. Among them there are", length(unique(omni_friend_network$user_id)), "unique omnivore users and",  length(unique(omni_friend_network$friends_id)), "unique friends.")

#581147 omnivore's actual friend pairs in total.4000 unique omnivore users and 369879 unique friends.


```


## 3.1 Friend LDA
```{r}
# Valid PH Business Data of Omnivores' Friends
# ============================================

#Business visits of omnivores' friends
omni_friend_business <- read.csv(paste0(data_dir,'freq_omni_friend_business0331.csv'))


unique_valid_omni_friend<-length(unique(omni_friend_business$friend_user_id))
unique_all_omni_friend<-length(unique(omni_friend_network$friends_id))

cat("\n There are",nrow(omni_friend_business),"business visiting records in total from ",unique_all_omni_friend,"unique omnivores' friends. Among them, there are",unique_valid_omni_friend,"unique friends have the valid business visiting records.\n")  


```



```{r}
# Topic of Omnivores
# ============================================
omni_user_topic_df <- user_topic_df|> 
  filter (user_id %in% omni_friend_network$user_id ) 
#dim(omni_user_topic_df)
 

# Topic of Omnivores' Friends
# ============================================
omni_friend_dtm <- omni_friend_business |>
  cast_dtm(friend_user_id, business_id, frequency)

omni_freind_lda_posterior <- topicmodels::posterior(object = lda,omni_friend_dtm)

omni_friend_topic_df <-omni_freind_lda_posterior$topics |> 
  as.data.frame() |> 
  rownames_to_column("user_id") 


cat("\n There are",nrow(user_topic_df),"users with topic distribution in total and there are", length(unique(user_topic_df$user_id)), "unique user_id.\n",

"Among them, there are ", nrow(omni_user_topic_df), "omnivores with topic distribution", "and there are and",length(omni_friend_topic_df$user_id), "friends with topic distribution and",length(unique(omni_friend_topic_df$user_id)),"unique friend_id.\n")
```


```{r}
# Combine Topics of Omnivores' & Omnivores' Friends
# ============================================

#Add user and friends' topics  (from "omni_friend_network")
omni_user_topic2 <-omni_friend_network |>
  left_join(omni_user_topic_df, by = "user_id")|>
  rename_with(~ paste0(., "_user"), -c(user_id, friends_id)) |> na.omit()
#dim(omni_user_topic2,2) #616760 pairs 


omni_user_friend_topic  <-omni_user_topic2 |>
   mutate(friends_id = str_replace(friends_id, "^[^[:alnum:]]+", "")) |>
   mutate(user_id = str_replace(user_id, "^[^[:alnum:]]+", "")) |> 
  left_join(omni_friend_topic_df,
     mutate(user_id = str_replace(user_id, "^[^[:alnum:]]+", "")),
      by = c("friends_id" = "user_id"),  suffix = c("_user", "_friend")) |> 
  rename_with(~ paste0(., "_friend"), -c(user_id, friends_id, ends_with("_user")))   |>  na.omit()


head(omni_user_friend_topic,2)


cat("\n There are",nrow(omni_friend_network),"pairs in total and there are", length(unique(omni_friend_network$user_id)), "unique users and",length(unique(omni_friend_network$friends_id)), "unique friends. Among them, there are ", nrow(omni_user_friend_topic), "valid pairs with topics", "and there are ",length(unique(omni_user_friend_topic$user_id)), "users with topic distribution and",length(unique(omni_user_friend_topic$friends_id)),"unique friends.\n")

```


```{r}
# Create Random Pairs
# ================================================
set.seed(123)

random_user_friend_network <- data.frame(user_id = character(), friends_id = character())

while(nrow(random_user_friend_network) < nrow(omni_user_friend_topic)) {
  pair <- data.frame(
    user_id = sample(omni_user_topic_df$user_id, 
                     nrow(omni_user_friend_topic) * 2, 
                     replace = TRUE),
    friends_id = sample(omni_friend_topic_df$user_id, 
                       nrow(omni_user_friend_topic) * 2, 
                       replace = TRUE)
  ) |>
    filter(user_id != friends_id) |>
    distinct() |>
    anti_join(random_user_friend_network, by = c("user_id", "friends_id"))
  
  need <- nrow(omni_user_friend_topic) - nrow(random_user_friend_network)
  random_user_friend_network <- bind_rows(random_user_friend_network, pair[1:min(need, nrow(pair)), ])
}




# Topic of Random Friends
# ============================================

random_user_topic2 <-random_user_friend_network |> 
  left_join(omni_user_topic_df, by = "user_id")|>
  rename_with(~ paste0(., "_user"),-c(user_id,friends_id))|>
  na.omit()

random_user_friend_topic<-random_user_topic2 |>
  mutate(friends_id = str_replace(friends_id, "^[^[:alnum:]]+", ""))|>
   mutate(user_id = str_replace(user_id, "^[^[:alnum:]]+", "")) |> 
  left_join(omni_friend_topic_df,
  mutate(user_id = str_replace(user_id, "^[^[:alnum:]]+", "")),
  by = c("friends_id" = "user_id"),  suffix = c("_user", "_friend")) |> 
   rename_with(~ paste0(., "_friend"), -c(user_id, friends_id, ends_with("_user"))) |> na.omit()

#dim(random_user_friend_topic) 
head(random_user_friend_topic,2)
#sum(is.na(random_user_friend_topic))

```


## 3.2 Cosine Similarity: Friends vs Random

```{r}
# Cosine Similarity of Omnivores' Friend Pairs
# ============================================
library(lsa)

omnivore_friends_similarities <- omni_user_friend_topic |>
  rowwise()  |> 
  mutate(
    cos_similarity = cosine(
      c_across(ends_with("_user")),
      c_across(ends_with("_friend"))
      )) |> 
  ungroup() |> 
  select(user_id, friends_id, cos_similarity)




# Cosine Similarity of Random Friends
# ============================================
random_friends_similarities<- random_user_friend_topic |> 
  rowwise() |>
  mutate(
    cos_similarity = cosine(
      c_across(ends_with("_user")),
      c_across(ends_with("_friend"))
      )) |> 
  ungroup() |> 
  select(user_id, friends_id, cos_similarity)

```


```{r}

t_test<-t.test(omnivore_friends_similarities$cos_similarity,
                  random_friends_similarities$cos_similarity,
                 alternative = "two.sided") 


tbl5 <- data.frame( Parameter = c(
    "Number of Friend Pairs", "Mean Similarity (Actual)", "Mean Similarity (Random)",
    "t-statistic (df)",
    "p-value"
  ),
    Value = c(
    nrow(omnivore_friends_similarities),
    round(mean(omnivore_friends_similarities$cos_similarity),3),
    round(mean(random_friends_similarities$cos_similarity),3),
    round(t_test$parameter,3),
    round(t_test$p.value,3)
  )) |> flextable() |> 
  font(fontname = "Times New Roman", part = "all")|> 
  fontsize(size = 10, part = "all") |> 
  bold(part = "header")|> 
  width(j = 1, width = 2.5) |>   
  #autofit() |> 
  set_caption("T-test Result of Taste Similarity") |> 
   add_footer_lines(
    "*** p < 0.001, ** p < 0.01, * p < 0.05\n Actual pairs = omnivore users and their actual friends; Random pairs = randomly matched pairs") |>
  fontsize(size = 9, part = "footer")

print(tbl5)
```



# Export 

```{r}
#output as rds 
#===================
output_path <-paste0(data_dir, 'Code for replication')
output_path_m<-paste0(data_dir, 'Code for replication/model')


#friends lda
saveRDS(object = list(omni_friend_dtm, 
                      omni_freind_lda_posterior, 
                      omni_user_friend_topic,
                      random_user_friend_topic,
                      t_test,
                      omnivore_friends_similarities, 
                      random_friends_similarities
                      ),
        file = paste0(output_path_m, '/omni_friend_lda_similarity.rds'))



 # write.csv(omni_friend_network,
 #          paste0(output_path,"/file/omnivore_friend_list.csv"),
 #                 row.names = FALSE)


```








```
